apiVersion: v1
kind: Pod
metadata:
  name: non-root-kestrel
  labels: 
    name: demo-2
spec:
  securityContext:
    runAsUser: 4242
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: container-host
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    env:
    - name: ASPNETCORE_URLS
      value: "http://+:5000"
